services:
  valkey:
    image: valkey/valkey:8.0.1-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - ${REDIS_PORT}:6379
  icecast:
    image: moul/icecast
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./icecast.xml:/etc/icecast2/icecast.xml
      - ./silence.mp3:/etc/silence.mp3
    environment:
      - ICECAST_HOSTNAME=localhost
    ports:
      - ${ICECAST_PORT}:8000
